#ifndef RUNTIME_SNAPSHOT_H
#define RUNTIME_SNAPSHOT_H

#include <stdbool.h>
#include <stdint.h>

#include "car_controller.h"
#include "car_state.h"
#include "fault.h"
#include "line_controller.h"
#include "mission_manager.h"
#include "motion_types.h"
#include "obstacle_avoidance.h"
#include "obstacle_monitor.h"

typedef struct {
    uint32_t timestamp_ms;
    CarState car_state;
    uint8_t mission_id;
    uint16_t action_index;
    MotionActionType action_type;
    MotionActionResult action_result;
    uint16_t action_error_code;
    uint16_t action_imu_wait_elapsed_ms;
    bool action_waiting_for_imu;
    TrackRunMode run_mode;
    uint8_t track_raw;
    int16_t track_error;
    bool line_control_v2_enabled;
    bool line_control_v2_config_valid;
    bool line_control_v2_dt_valid;
    uint8_t line_control_sensor_pattern;
    uint8_t line_control_active_count;
    int16_t line_control_raw_error;
    float line_control_filtered_error;
    float line_control_derivative;
    float line_control_correction_raw;
    int16_t line_control_correction;
    int16_t line_control_left_command;
    int16_t line_control_right_command;
    bool line_control_left_low_speed_zeroed;
    bool line_control_right_low_speed_zeroed;
    LineControlState line_control_state;
    LineTurnDirection line_control_turn_mark;
    bool line_control_turn_mark_valid;
    uint32_t line_control_lost_elapsed_ms;
    bool line_control_recover_timeout;
    LineControlStopReason line_control_stop_reason;
    uint8_t line_control_last_valid_pattern;
    int16_t line_control_last_valid_error;
    uint32_t line_control_turn_mark_update_count;
    float yaw_deg;
    float gyro_z_dps;
    float imu_gyro_bias_dps;
    int16_t imu_raw_gyro_z_counts;
    float imu_gyro_z_before_bias_dps;
    float imu_gyro_z_after_bias_dps;
    float imu_angle_increment_deg;
    float imu_gyro_sensitivity_lsb_per_dps;
    uint8_t imu_gyro_config_readback;
    uint8_t imu_gyro_fs_sel;
    uint16_t imu_gyro_full_scale_dps;
    int8_t imu_yaw_axis_sign;
    uint32_t imu_sample_dt_ms;
    float imu_sample_dt_s;
    bool imu_initialized;
    bool imu_calibrated;
    bool imu_valid;
    bool imu_stale;
    bool imu_dt_valid;
    bool imu_short_gap_compensating;
    bool imu_integration_applied;
    bool imu_integration_history_valid;
    uint32_t imu_update_count;
    uint32_t imu_successful_read_count;
    uint32_t imu_integration_count;
    uint32_t imu_integration_skip_count;
    uint32_t imu_history_rebuild_count;
    uint32_t imu_dt_invalid_skip_count;
    uint32_t imu_read_fail_skip_count;
    uint32_t imu_gyro_invalid_skip_count;
    uint32_t imu_yaw_reset_count;
    uint32_t imu_cumulative_elapsed_ms;
    uint32_t imu_cumulative_integrated_dt_ms;
    float imu_cumulative_angle_increment_deg;
    uint32_t imu_last_success_age_ms;
    uint32_t imu_read_fail_count;
    uint32_t imu_consecutive_read_fail_count;
    uint32_t imu_gyro_range_error_count;
    ObstacleState obstacle_state;
    bool safety_hold;
    bool external_hold;
    ObstacleAvoidState avoidance_state;
    FaultCode fault_code;
    uint16_t fault_detail;
    uint16_t fault_context;
    uint32_t turn_to_yaw_elapsed_ms;
    float turn_to_yaw_error_deg;
    uint16_t heading_imu_invalid_elapsed_ms;
    uint32_t app_missed_count;
    uint32_t app_drop_count;
    uint32_t app_overrun_count;
    uint32_t uart_overflow_count;
    bool heartbeat_seen;
    bool watchdog_tripped;
    bool hardware_watchdog_enabled;
    uint32_t heartbeat_age_ms;
    int32_t left_delta_pulse;
    int32_t right_delta_pulse;
    int64_t left_total_pulse;
    int64_t right_total_pulse;
    float left_raw_speed_cmps;
    float right_raw_speed_cmps;
    float left_speed_cmps;
    float right_speed_cmps;
    float left_total_distance_cm;
    float right_total_distance_cm;
    float center_distance_cm;
    bool wheel_estimator_valid;
    bool wheel_estimator_stale;
    bool wheel_estimator_overflow;
    uint32_t wheel_estimator_error_flags;
    uint32_t encoder_ppr_x2;
    float wheel_diameter_cm;
    float wheel_track_cm;
    int8_t left_encoder_direction;
    int8_t right_encoder_direction;
    bool motor_control_enabled;
    bool motor_control_valid;
    bool motor_control_error_latched;
    bool motor_control_safety_inhibited;
    bool motor_control_target_refresh_timeout;
    uint32_t motor_control_error_flags;
    uint32_t motor_control_estimator_error_flags;
    uint32_t motor_control_target_age_ms;
    int16_t motor_control_left_normalized_target;
    int16_t motor_control_right_normalized_target;
    float motor_control_left_raw_target_cmps;
    float motor_control_right_raw_target_cmps;
    float motor_control_left_ramped_target_cmps;
    float motor_control_right_ramped_target_cmps;
    float motor_control_left_measured_cmps;
    float motor_control_right_measured_cmps;
    float motor_control_left_error_cmps;
    float motor_control_right_error_cmps;
    float motor_control_left_integral;
    float motor_control_right_integral;
    float motor_control_left_proportional_term;
    float motor_control_right_proportional_term;
    float motor_control_left_integral_term;
    float motor_control_right_integral_term;
    float motor_control_left_feedforward_term;
    float motor_control_right_feedforward_term;
    float motor_control_left_kp_used;
    float motor_control_right_kp_used;
    int16_t motor_control_left_output;
    int16_t motor_control_right_output;
    bool motor_control_left_saturated;
    bool motor_control_right_saturated;
    bool motor_control_left_overspeed_gain_active;
    bool motor_control_right_overspeed_gain_active;
    bool motor_control_left_error_sign_changed;
    bool motor_control_right_error_sign_changed;
    bool motor_control_left_integral_releasing;
    bool motor_control_right_integral_releasing;
} RuntimeSnapshot;

void RuntimeSnapshot_Init(void);
void RuntimeSnapshot_Update(uint32_t timestamp_ms);
const RuntimeSnapshot *RuntimeSnapshot_Get(void);

#endif
